import { createClient } from "@supabase/supabase-js"

export const supabase = createClient("https://wxwkfcytvmlhhfacebbu.supabase.co", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4d2tmY3l0dm1saGhmYWNlYmJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODU3MjIyMDQsImV4cCI6MjAwMTI5ODIwNH0.Jhz2qPv3vUWmOmnV3fKLjcgkYjwNyazH2VW6q_DKr1I")